site_name: Angel Beats! Docs
#site_url:
markdown_extensions:
  - admonition
theme:
  name: 'readthedocs'
nav:
- Welcome: index.md
- Suggestions: suggestionsMods.md
- Ids: ids-fan.md
- Old fan colours: fancolours-old.md